name: Boost Brakeman Scanner
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize

env:
  test: TRUE
  test2: true
  test3: True
  test4: "true"
  test5: "true"
  test6: ${{ true == true }}

jobs:
  scanner:
    name: boost
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute boost-brakeman
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_endpoint: ${{ env.test == true }}
          api_token: ${{ env.test1 == true }}
          additional_args: ${{ env.test2 == true }}
          cli_version: ${{ env.test3 == true }}
          main_branch: ${{ env.test4 == true }}
          log_level: ${{ env.test5 == true }}
          scan_timeout: ${{ env.test6 == true }}
